PR for feature branch
praz99/ror_private_events pull request #5
Opened 2020-08-27 14:22 UTC by praz99

In this project we

- added user sessions.

- generated controller for user, event, and event attendance.

- created associations between users and events.

- added RSpec test for model validations and associations.

- added RSpec and Capybara for testing features and integrations.

2020-08-27 17:12 UTC, lekegitrepo requested changes
### Status: Request changes :recycle:
#### Hi @praz99 and @okikiola11 :clap: :clap:
#### You have done a good job so far, however, there are still some requirements you need to fix before this project can be approved. Check my comments below.

**_- The event's show should page displays the list of attendants ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/login_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))_**

**_- The user should provide email ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/associations/user_can_create_events_requirement.png) from [Odin](https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations))_**

**_Check the remaining comments below :point_down:_** 

#### _Reviewed by Temitayo Adeleke._

2020-08-27 17:12 UTC, lekegitrepo commented on db/schema.rb
> +  add_foreign_key "event_attendings", "users", column: "event_attendee_id"
- The following columns of the database should be index
  - creator_id
  - event_attendings

2020-08-27 17:12 UTC, lekegitrepo commented on app/views/shared/_error_messages.html.erb
> +<% end %>
- View-related logic can be encapsulated in View helpers (app/helpers/*_helper.rb)
- There should be absolutely NO logic in views.

2020-08-27 17:12 UTC, lekegitrepo commented on app/views/layouts/_header.html.erb
> +      <% end %>
- View-related logic can be encapsulated in View helpers (app/helpers/*_helper.rb)
- There should be absolutely NO logic in views.

2020-08-27 17:12 UTC, lekegitrepo commented on app/views/event_attendings/new.html.erb
> +<!--<%= f.collection_check_boxes :event_attendee_id, User.all, :id, :username %>-->
- It’s better to delete commented piece of codes. If you need to review a previous version of your code, use git history

2020-08-27 17:20 UTC, lekegitrepo commented on app/controllers/event_attendings_controller.rb
> +# end
- It’s better to delete commented piece of codes. If you need to review a previous version of your code, use git history

2020-08-28 11:12 UTC, rOluochKe approved these changes
Hello Team
### Well done, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project, good luck with the next one.
- Happy coding!

2020-08-28 12:15 UTC, merged